sudo: required
dist: bionic

language: go

go:
  - "1.12"

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-10-postgis-2.3    
    - postgresql-client-10

env:
  global:
    - GO111MODULE=on
    - PGPORT=5432
    
  matrix:
    - PGDB=10 RELEASE=true

services:
  - redis-server
  - postgresql

before_script:
  - psql -U postgres -c "create extension postgis;"
  - psql -U postgres -c "create extension postgis_topology;"
  - psql -U postgres -c "create extension hstore;"
  - psql -U postgres -c "CREATE USER mailroom_test PASSWORD 'temba';"
  - psql -U postgres -c "ALTER ROLE mailroom_test WITH SUPERUSER;"
  - psql -U postgres -c "CREATE DATABASE mailroom_test;"

script:
  - go test -p=1 -coverprofile=coverage.text -covermode=atomic github.com/nyaruka/mailroom/...
  - df -h

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - rm coverage.text

before_deploy:
  - export GOFLOW_VERSION=$(grep goflow go.mod | cut -d" " -f2)
  - curl https://codeload.github.com/nyaruka/goflow/tar.gz/$GOFLOW_VERSION | tar --wildcards --strip=1 -zx "*/docs/*"

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $RELEASE = true

