sudo: required 
dist: trusty

language: go

addons:
  apt:
    packages:
      - redis-server
      - postgresql-9.6-postgis-2.3
  postgresql: '9.6'
  
go:
- "1.11"

services:
- redis-server

before_install:
  - sudo sed -e 's/^bind.*/bind 127.0.0.1/' /etc/redis/redis.conf > redis.conf
  - sudo mv redis.conf /etc/redis
  - sudo service redis-server start
  - echo PING | nc localhost 6379
  - df -h

before_script:
- psql -U postgres -c "CREATE USER temba;"
- psql -U postgres -c "ALTER ROLE temba WITH SUPERUSER;"
- psql -U postgres -c "CREATE DATABASE temba;"

script:
- go test -p=1 -coverprofile=coverage.text -covermode=atomic github.com/nyaruka/mailroom/...
- df -h

after_success:
- bash <(curl -s https://codecov.io/bash)
- rm coverage.text

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

